import {
  LayoutDashboard,
  Pill,
  Package,
  AlertTriangle,
  CalendarX,
  Ban,
  DollarSign,
  History,
  Truck,
  CheckCircle2,
  ShieldCheck,
  AtSign,
  KeyRound,
  Smartphone,
  Upload,
  Plus,
  IdCard,
  Building2,
  Stethoscope,
  Mail,
  Lock,
  ArrowRight,
  MailCheck,
  HelpCircle,
  LogOut,
  User,
  Settings,
  ArrowLeftRight,
  ShoppingCart,
  BarChart3,
  Users,
  Receipt,
  Bell,
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Eye,
  EyeOff,
  SlidersHorizontal,
  Download,
  Star,
  X,
  Check,
  CirclePlus,
  CircleMinus,
  TrendingUp,
  TrendingDown,
  EllipsisVertical,
  UserPlus,
  Pencil,
  Shield,
  UserCog,
  UserX,
  Calendar,
  ExternalLink,
  CircleAlert,
  MapPin,
  Thermometer,
  Barcode,
  ScanLine,
  ClipboardList,
  ClipboardClock,
  Info,
  Clock,
  Bot,
  Send,
  FileUp,
  FileText,
  Trash2,
  ArrowUpRight,
  type LucideIcon,
} from "lucide-react";

/** Maps the app's icon names to Lucide components. */
const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  medication: Pill,
  inventory_2: Package,
  warning: AlertTriangle,
  event_busy: CalendarX,
  block: Ban,
  payments: DollarSign,
  history: History,
  local_shipping: Truck,
  check_circle: CheckCircle2,
  verified_user: ShieldCheck,
  alternate_email: AtSign,
  key: KeyRound,
  smartphone: Smartphone,
  upload: Upload,
  add: Plus,
  badge: IdCard,
  domain: Building2,
  medical_services: Stethoscope,
  mail: Mail,
  lock: Lock,
  arrow_forward: ArrowRight,
  mark_email_read: MailCheck,
  lock_reset: KeyRound,
  help: HelpCircle,
  logout: LogOut,
  person: User,
  settings: Settings,
  swap_horiz: ArrowLeftRight,
  shopping_cart: ShoppingCart,
  bar_chart: BarChart3,
  group: Users,
  receipt_long: Receipt,
  notifications: Bell,
  search: Search,
  expand_more: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  filter_list: SlidersHorizontal,
  download: Download,
  star: Star,
  close: X,
  check: Check,
  add_circle: CirclePlus,
  remove_circle: CircleMinus,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  more_vert: EllipsisVertical,
  person_add: UserPlus,
  edit: Pencil,
  shield: Shield,
  manage_accounts: UserCog,
  person_off: UserX,
  calendar_month: Calendar,
  open_in_new: ExternalLink,
  error: CircleAlert,
  place: MapPin,
  thermostat: Thermometer,
  barcode: Barcode,
  scan: ScanLine,
  clinical_notes: ClipboardList,
  assignment_clock: ClipboardClock,
  info: Info,
  schedule: Clock,
  bot: Bot,
  smart_toy: Bot,
  send: Send,
  upload_file: FileUp,
  description: FileText,
  delete: Trash2,
  arrow_outward: ArrowUpRight,
  visibility: Eye,
  visibility_off: EyeOff,
};

type IconProps = {
  /** A key of ICONS, e.g. "lock". */
  name: string;
  size?: number;
  className?: string;
};

/** Decorative (aria-hidden) icon. Icon-only buttons need their own aria-label. */
export default function Icon({ name, size = 19, className = "" }: IconProps) {
  const Cmp = ICONS[name];
  if (!Cmp) {
    // Fail loudly in dev rather than silently rendering nothing.
    console.warn(`Icon: no Lucide mapping for "${name}"`);
    return null;
  }
  return <Cmp aria-hidden="true" width={size} height={size} className={className} strokeWidth={2} />;
}
